// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionType.
const (
	ActionTypeFlag   ActionType = "flag"
	ActionTypeReveal ActionType = "reveal"
)

// Defines values for BoardState.
const (
	Completed  BoardState = "completed"
	Failed     BoardState = "failed"
	InProgress BoardState = "inProgress"
	NotStarted BoardState = "notStarted"
)

// Defines values for GameState.
const (
	Created  GameState = "created"
	Finished GameState = "finished"
	Started  GameState = "started"
)

// Defines values for TileState.
const (
	TileStateBomb   TileState = "bomb"
	TileStateEmpty  TileState = "empty"
	TileStateFlag   TileState = "flag"
	TileStateHidden TileState = "hidden"
	TileStateN1     TileState = "1"
	TileStateN2     TileState = "2"
	TileStateN3     TileState = "3"
	TileStateN4     TileState = "4"
	TileStateN5     TileState = "5"
	TileStateN6     TileState = "6"
	TileStateN7     TileState = "7"
	TileStateN8     TileState = "8"
)

// Action An action on a board
type Action struct {
	Type ActionType `json:"type"`
	XPos int        `json:"xPos"`
	YPos int        `json:"yPos"`
}

// ActionType defines model for Action.Type.
type ActionType string

// Board An individual MineSpeeder board, to be controlled by an individual player
type Board struct {
	Height                 int        `json:"height"`
	Id                     string     `json:"id"`
	NumberOfBombs          int        `json:"numberOfBombs"`
	NumberOfRemainingBombs int        `json:"numberOfRemainingBombs"`
	NumberOfRemainingTiles int        `json:"numberOfRemainingTiles"`
	NumberOfTiles          int        `json:"numberOfTiles"`
	State                  BoardState `json:"state"`
	Tiles                  []Tile     `json:"tiles"`
	Width                  int        `json:"width"`
}

// BoardState defines model for Board.State.
type BoardState string

// BoardOptions defines model for boardOptions.
type BoardOptions struct {
	Height        int `json:"height"`
	NumberOfBombs int `json:"numberOfBombs"`
	Width         int `json:"width"`
}

// CreateGameRequest defines model for createGameRequest.
type CreateGameRequest struct {
	BoardOptions   BoardOptions `json:"boardOptions"`
	Id             string       `json:"id"`
	NumberOfBoards int          `json:"numberOfBoards"`
}

// Game defines model for game.
type Game struct {
	BoardOptions BoardOptions `json:"boardOptions"`
	Boards       []Board      `json:"boards"`

	// Duration seconds of game duration, from started to finished
	Duration       int       `json:"duration"`
	Id             string    `json:"id"`
	NumberOfBoards int       `json:"numberOfBoards"`
	State          GameState `json:"state"`
}

// GameState defines model for Game.State.
type GameState string

// Tile defines model for tile.
type Tile struct {
	State TileState `json:"state"`
	XPos  int       `json:"xPos"`
	YPos  int       `json:"yPos"`
}

// TileState defines model for Tile.State.
type TileState string

// PostV1GamesJSONRequestBody defines body for PostV1Games for application/json ContentType.
type PostV1GamesJSONRequestBody = CreateGameRequest

// PostV1GamesGameIdBoardsBoardIdActionsJSONRequestBody defines body for PostV1GamesGameIdBoardsBoardIdActions for application/json ContentType.
type PostV1GamesGameIdBoardsBoardIdActionsJSONRequestBody = Action

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creating a game
	// (POST /v1/games)
	PostV1Games(w http.ResponseWriter, r *http.Request)
	// Get a specific game
	// (GET /v1/games/{gameId})
	GetV1GamesGameId(w http.ResponseWriter, r *http.Request, gameId string)
	// Get all boards for a game
	// (GET /v1/games/{gameId}/boards)
	GetV1GamesGameIdBoards(w http.ResponseWriter, r *http.Request, gameId string)
	// Get a specific board
	// (GET /v1/games/{gameId}/boards/{boardId})
	GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request, gameId string, boardId string)
	// Create an action on the board
	// (POST /v1/games/{gameId}/boards/{boardId}/actions)
	PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request, gameId string, boardId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Creating a game
// (POST /v1/games)
func (_ Unimplemented) PostV1Games(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific game
// (GET /v1/games/{gameId})
func (_ Unimplemented) GetV1GamesGameId(w http.ResponseWriter, r *http.Request, gameId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all boards for a game
// (GET /v1/games/{gameId}/boards)
func (_ Unimplemented) GetV1GamesGameIdBoards(w http.ResponseWriter, r *http.Request, gameId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific board
// (GET /v1/games/{gameId}/boards/{boardId})
func (_ Unimplemented) GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request, gameId string, boardId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an action on the board
// (POST /v1/games/{gameId}/boards/{boardId}/actions)
func (_ Unimplemented) PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request, gameId string, boardId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostV1Games operation middleware
func (siw *ServerInterfaceWrapper) PostV1Games(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1Games(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1GamesGameId operation middleware
func (siw *ServerInterfaceWrapper) GetV1GamesGameId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1GamesGameId(w, r, gameId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1GamesGameIdBoards operation middleware
func (siw *ServerInterfaceWrapper) GetV1GamesGameIdBoards(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1GamesGameIdBoards(w, r, gameId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetV1GamesGameIdBoardsBoardId operation middleware
func (siw *ServerInterfaceWrapper) GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "boardId" -------------
	var boardId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "boardId", runtime.ParamLocationPath, chi.URLParam(r, "boardId"), &boardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "boardId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1GamesGameIdBoardsBoardId(w, r, gameId, boardId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostV1GamesGameIdBoardsBoardIdActions operation middleware
func (siw *ServerInterfaceWrapper) PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "boardId" -------------
	var boardId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "boardId", runtime.ParamLocationPath, chi.URLParam(r, "boardId"), &boardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "boardId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1GamesGameIdBoardsBoardIdActions(w, r, gameId, boardId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/games", wrapper.PostV1Games)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/games/{gameId}", wrapper.GetV1GamesGameId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/games/{gameId}/boards", wrapper.GetV1GamesGameIdBoards)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/games/{gameId}/boards/{boardId}", wrapper.GetV1GamesGameIdBoardsBoardId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/games/{gameId}/boards/{boardId}/actions", wrapper.PostV1GamesGameIdBoardsBoardIdActions)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTY/bNhD9K8S0R3ZlJ/2Cb94ejD0UMXaLXoIcKHEkM5VIhaS8NQz/92JIyV+SdpUm",
	"BvZk2RySM++9eWPtITNVbTRq72CxB5dtsBLhUWReGU1PEl1mVR2/wlKzuMSMZoKlRlgJHGprarReYdjs",
	"dzXSJ+qmgsVHsLhFUQKHvBQFfOJtADhvlS7gwOHftTnbCUp7LNDSym5k5cDB4pdGWZR0RTigjW7PP91j",
	"0s+YeTot5jtUldJSbZVsRMn+VBqfakSJNhbImTcsRZYZ7a0pS5Qs3TFxsakuxQ5tD4oNqmLjh0tT8uz3",
	"Exa6qVK0H/J7U6UjoHQhj1gJpZUuvib2L1XiK7EvhDgv/AW52vgnL6xH0oHSa2sKi45YIHGVGBdyoUqU",
	"g9z77jLlsQoPP1rMYQE/JCd5Jq02E4oOu+Ixwlqxo+/PSvrNBKHE23hHTLfxGvZrLEZxHCWjgyrwPKrF",
	"D0GCoerpwpmgkKlwvALDUN6ZReFxJSp8xC8NOt9P/rq0lwi9iJ3SFcLKKY5wteEK71FWClHh9y0oPWY8",
	"SeDRogYULhsrhk3ZYWa0dMzkjNJnXSRnuTUVc7E9ycRypZXbhI78H340hvyAK0SRyNgFrTkcL++7wGvc",
	"da10xKBHZ9qFjvAafKPHay/vOXB4BxzeA4efgcMvwOFX4PAbcPidbENJiXQ9VrXfdSONrq/S20y2rvTz",
	"CdcvkHYpnZu+OO5F9g9qyZbrB+ZqzFhuLPMbvBhzQTY/0UgzulQ6LrpnxBotU9rVlA1LhfclhmASkPIE",
	"KZyds1w/AIctWhfvnt/N7mZUq6lRi1rBAt7fze4I4Fr4TSg/2c4TOjF6oIl2QhwFoh8kLGBtnP97vgpB",
	"ERx0/t7IHYXSUEYddom6LlUW9iWfXeyU2FavNV3f0w6XPHjbYPjB1Ua7mOy72fy7JRAwDXdesvfUZBk6",
	"lzdluWNtUzHB2nAOrqkqYXewgD9oUenifPWIbbKnjwd5oDwKHMB4hR3EqxAZKLKiQo/WweLjHhTlQ7TR",
	"lAguCUUXegkUPyv6utE/9UCc3RzE5RG5AdxW6JkInaFylb2EXXJy8kkQHt3rTQL5LcOoD3GslSk9LM4A",
	"clnGv9MuWJCYAHWyD59fo9uYyH3cBjcUWwtNH4pH9I3Vrns7ijOYDNeh3bYGPyq/I+A30QwfPCg9A2uy",
	"+qbRlsSXxWnePkDgMuvm+1vH4zZzqX0Nnz6Mrowvvqo/C3d0QHc2UIYmCNKfgNMrPun2qPTDfwEAAP//",
	"M7H41DEQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
