// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionType.
const (
	ActionTypeFlag   ActionType = "flag"
	ActionTypeReveal ActionType = "reveal"
)

// Defines values for TileState.
const (
	TileStateBomb   TileState = "bomb"
	TileStateEmpty  TileState = "empty"
	TileStateFlag   TileState = "flag"
	TileStateHidden TileState = "hidden"
	TileStateN1     TileState = "1"
	TileStateN2     TileState = "2"
	TileStateN3     TileState = "3"
	TileStateN4     TileState = "4"
	TileStateN5     TileState = "5"
	TileStateN6     TileState = "6"
	TileStateN7     TileState = "7"
	TileStateN8     TileState = "8"
)

// Action An action on a board
type Action struct {
	Type ActionType `json:"type"`
	XPos int        `json:"xPos"`
	YPos int        `json:"yPos"`
}

// ActionType defines model for Action.Type.
type ActionType string

// Board An individual MineSpeeder board, to be controlled by an individual player
type Board struct {
	Height                 int    `json:"height"`
	NumberOfBombs          int    `json:"numberOfBombs"`
	NumberOfRemainingBombs int    `json:"numberOfRemainingBombs"`
	NumberOfRemainingTiles int    `json:"numberOfRemainingTiles"`
	NumberOfTiles          int    `json:"numberOfTiles"`
	Tiles                  []Tile `json:"tiles"`
	Width                  int    `json:"width"`
}

// Tile defines model for tile.
type Tile struct {
	State TileState `json:"state"`
	XPos  int       `json:"xPos"`
	YPos  int       `json:"yPos"`
}

// TileState defines model for Tile.State.
type TileState string

// PostV1GamesGameIdBoardsBoardIdActionsJSONRequestBody defines body for PostV1GamesGameIdBoardsBoardIdActions for application/json ContentType.
type PostV1GamesGameIdBoardsBoardIdActionsJSONRequestBody = Action

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GET a specific board
	// (GET /v1/games/{gameId}/boards/{boardId})
	GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request, gameId string, boardId string)
	// Create an action on the board
	// (POST /v1/games/{gameId}/boards/{boardId}/actions)
	PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request, gameId string, boardId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GET a specific board
// (GET /v1/games/{gameId}/boards/{boardId})
func (_ Unimplemented) GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request, gameId string, boardId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an action on the board
// (POST /v1/games/{gameId}/boards/{boardId}/actions)
func (_ Unimplemented) PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request, gameId string, boardId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetV1GamesGameIdBoardsBoardId operation middleware
func (siw *ServerInterfaceWrapper) GetV1GamesGameIdBoardsBoardId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "boardId" -------------
	var boardId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "boardId", runtime.ParamLocationPath, chi.URLParam(r, "boardId"), &boardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "boardId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetV1GamesGameIdBoardsBoardId(w, r, gameId, boardId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostV1GamesGameIdBoardsBoardIdActions operation middleware
func (siw *ServerInterfaceWrapper) PostV1GamesGameIdBoardsBoardIdActions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "gameId" -------------
	var gameId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "gameId", runtime.ParamLocationPath, chi.URLParam(r, "gameId"), &gameId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	// ------------- Path parameter "boardId" -------------
	var boardId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "boardId", runtime.ParamLocationPath, chi.URLParam(r, "boardId"), &boardId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "boardId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1GamesGameIdBoardsBoardIdActions(w, r, gameId, boardId)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/games/{gameId}/boards/{boardId}", wrapper.GetV1GamesGameIdBoardsBoardId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/games/{gameId}/boards/{boardId}/actions", wrapper.PostV1GamesGameIdBoardsBoardIdActions)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVTW/bOBD9K8TsHrmWnexuC93sogh8KGqkQS9BDpQ4kplKJEtSTgVD/70YUm78lY8C",
	"LdATJXDe48ybx+EWStNao1EHD/kWfLnGVsRPUQZlNH1J9KVTNv3CXLO0xYxmghVGOAkcrDMWXVAYwaG3",
	"SCvqroX8FhxuUDTAoWpEDXd8DAAfnNI1DBy+rcweEpQOWKOjnf6JnYGDw6+dcijpiEgwRo/8j+eY4h7L",
	"QGwp33NVKS3VRslONOyD0vjJIkp0qUDOgmEFstLo4EzToGRFz8QByDaiR3cixRpVvQ7nS9NdW6D7WC1M",
	"W/jnQ66xFUorXf9M7I1q8IXYZ0LCbksFbOPH3w4ryOGv7NE12WiZjKIjKvEI50RP/w9KhvUr+pdO4zu9",
	"dsBjkY4zf7LqJ6U754qYfL49ap0PIhzYeAYcLoDDJXD4Fzj8Bxz+Bw5vgMNbyl1JiRo4YGtDv7M7ma4t",
	"fo/rU4r8wP2nBRJK6cqc+n4hyi+oJZuvlsxbLFllHAtrPLgCtWiR/UN2N7pROm36B0SLjintLWXDChFC",
	"gzGYLqAKJCns8cxXS+CwQefT2bPJdDKlWo1FLayCHC4n0wkJbEVYx/KzzSwjRp9taVnKIYsX0mfbuC7l",
	"QGE1xhtGzRNU2VJCDlcYPs+uCHwVoYsIXCQYkI7eGu1Try+mU1rogqOOZMLaRpWRLrv3aRQms790FdKM",
	"iaofqn2NoXPa78Ymq5xpo9oe3Wbsru/aVrie8n9/w0TsiqpUOU7agcRxosWAzkN+uwVFzCQYWZ7EzyFJ",
	"BftWCa5Dvpf/kRUHfpao2BPrtUx3A39N27L0ikTxrfFn+rcy/pkGzkf4n69HCkYfFkb2v8xk4/s8HE4E",
	"SmY4sfbszIOX3vAH4VnpUASUzHdlid5XXdP0R1Z8F0NoAjy+/eTbH04fvgcAAP//RpxQ60oIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
